const functions = new Set([
    'linear-gradient',
    'radial-gradient',
    'conic-gradient',
    'repeating-linear-gradient',
    'repeating-radial-gradient',
    'repeating-conic-gradient',
    'image-set',
    'image',
    'url',
    'element',
    'rgb',
    'rgba',
    'hsl',
    'hsla',
    'hwb',
    'color-mod',
    'circle',
    'ellipse',
    'inset',
    'polygon',
    'path',
    'blur',
    'brightness',
    'contrast',
    'drop-shadow',
    'grayscale',
    'hue-rotate',
    'invert',
    'opacity',
    'saturate',
    'sepia',
    'matrix',
    'matrix3d',
    'perspective',
    'rotate',
    'rotate3d',
    'rotateX',
    'rotateY',
    'rotateZ',
    'scale',
    'scale3d',
    'scaleX',
    'scaleY',
    'scaleZ',
    'skew',
    'skewX',
    'skewY',
    'translate',
    'translateX',
    'translateY',
    'translateZ',
    'translate3d',
    'calc',
    // not support min, max, toggle
    // 'min',
    // 'max',
    // 'toggle',
    'mixmax',
    'repeat',
    'cubic-bezier',
    'steps',
    'counter',
    'counters',
    'var',
    'symbols',
    'attr'
]);

export default function isCssFunction(functionName: string): boolean {
    functionName = functionName.replace(/^(-webkit-|-moz-|-ms-|-o-|-webkit-)/, '');
    return functions.has(functionName);
}
