extends:
    - gitmoji

parserPreset:
    parserOpts:
        headerPattern: '^(\w+)(?:\((.*?)\))?:\s:\w+:\s((?:.*(?=\())|.*)(?:\(#(\d*)\))?'
        headerCorrespondence:
            - type
            - scope
            - subject
            - ticket

rules:
    type-enum:
        - 2
        - always
        -
            - feat
            - fix
            - style
            - prune
            - ui
            - docs
            - test
            - lint
            - wip
            - perf
            - refactor
            - revert
            - config
            - merge
            - release
            - init

    type-case:
        - 2
        - always
        - lower-case

    scope-enum:
        - 2
        - always
        -
            - mew
            - styleguide
            - eslint-plugin
            - mpxml-eslint-parser
            - eslint-plugin-mini
            - dom
            - htmlparser2
            - html-code-gen
            - html-nest-rule
            - manis
            - htmlint
            - stylelint
            - cli
            - vscode
            - loader
            - sonar


    scope-case:
        - 2
        - always
        - lower-case

    subject-full-stop:
        - 0
        - never

    subject-case:
        - 0
        - never

