root: true
extends:
    - plugin:@mewjs/typescript

parserOptions:
    project: ['./tsconfig.json', './test/tsconfig.json']
rules:
    id-denylist: 0
    no-magic-numbers: 0
    class-methods-use-this: 0
    no-proto: 0
    no-sequences: 0
    '@typescript-eslint/no-use-before-define': 0
    '@typescript-eslint/no-magic-numbers': 0
    '@typescript-eslint/no-dynamic-delete': 0
