extends:
    - plugin:@mewjs/typescript
env:
    commonjs: true
    jest: true

rules:
    import/no-commonjs: 0
    import/unambiguous: 0
    object-shorthand: 0
    max-lines-per-function: 0
    max-lines: 0
    complexity: [1, 25]
