exports.eslintRulesDoc = {
    'default': 'https://eslint.org/docs/rules/{rule}',
    'import/': 'https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/{rule}.md',
    'babel/': 'https://github.com/babel/eslint-plugin-babel#rules',
    'react/': 'https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/{rule}.md',
    'jsx-a11y/': 'https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/{rule}.md',
    'react-native/': 'https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/{rule}.md',
    'vue/': 'https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/{rule}.md',
    '@typescript-eslint/': 'https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/{rule}.md'
};

exports.stylelintRulesDoc = {
    'default': 'https://stylelint.io/user-guide/rules/{rule}',
    'mew/': 'https://github.com/mewjs/mew/blob/master/packages/stylelint/README.md#{rule}',
};


exports.eslintRulesNames = {
    'no-misleading-character-class': 'Disallow characters which are made with multiple code points in character class syntax',
    'no-async-promise-executor': 'disallow using an async function as a Promise executor',
    'require-atomic-updates': 'Disallow assignments that can lead to race conditions due to usage of await or yield',
    'no-useless-catch': 'Disallow unnecessary catch clauses',
    'max-lines-per-function': 'enforce a maximum function length',
    'prefer-object-spread': 'Prefer use of an object spread over Object.assign',
    'babel/new-cap': 'require constructor names to begin with a capital letter',
    'babel/camelcase': 'Require CamelCase',
    'babel/no-invalid-this': 'Disallow this keywords outside of classes or class-like objects.',
    'babel/object-curly-spacing': 'enforce consistent spacing inside braces',
    'babel/quotes': 'require quotes around object literal property names',
    'babel/semi': 'require semicolons',
    'babel/no-unused-expressions': 'Disallow Unused Expressions',
    'babel/valid-typeof': 'enforce comparing typeof expressions against valid strings',
    'react/jsx-fragments': 'Enforce shorthand or standard form for React fragments',
    'react-hooks/rules-of-hooks': 'react rules of hooks',
    'jsx-a11y/control-has-associated-label': 'Enforce that a control (an interactive element) has a text label.',
    'jsx-a11y/label-has-associated-control': 'Enforce that a label tag has a text label and an associated control.',
    'react-native/no-color-literals': 'Detect color literals in styles',
    'react-native/no-inline-styles': 'Detect inline styles in components',
    'react-native/no-raw-text': 'Detect raw text outside of Text component',
    'react-native/no-unused-styles': 'Detect unused StyleSheet rules in React components',
    'react-native/split-platform-components': 'Enforce using platform specific filenames when necessary',
    '@typescript-eslint/no-unused-vars': 'Disallow unused variables',
    '@typescript-eslint/array-type': 'Requires using either T[] or Array<T> for arrays',
    '@typescript-eslint/ban-types': 'Bans specific types from being used',
    '@typescript-eslint/member-delimiter-style': 'Require a specific member delimiter style for interfaces and type literals',
    '@typescript-eslint/no-dynamic-delete': 'Disallow the delete operator with computed key expressions',
    '@typescript-eslint/no-explicit-any': 'Disallow usage of the any type',
    '@typescript-eslint/no-extra-non-null-assertion': 'Disallow extra non-null assertion',
    '@typescript-eslint/no-extraneous-class': 'Forbids the use of classes as namespaces',
    '@typescript-eslint/no-for-in-array': 'Disallow iterating over an array with a for-in loop',
    '@typescript-eslint/no-inferrable-types': 'Disallows explicit type declarations for variables or parameters initialized to a number, string, or boolean',
    '@typescript-eslint/no-namespace': 'Disallow the use of custom TypeScript modules and namespaces ',
    '@typescript-eslint/no-var-requires': 'Disallows the use of require statements except in import statements ',
    '@typescript-eslint/prefer-for-of': 'Prefer a ‘for-of’ loop over a standard ‘for’ loop if the index is only used to access the array being iterated',
    '@typescript-eslint/prefer-namespace-keyword': 'Require the use of the namespace keyword instead of the module keyword to declare custom TypeScript modules',
    '@typescript-eslint/prefer-optional-chain': 'Prefer using concise optional chain expressions instead of chained logical ands',
    '@typescript-eslint/triple-slash-reference': 'Sets preference level for triple slash directives versus ES6-style import declarations',
    '@typescript-eslint/unified-signatures': 'Warns for any two overloads that could be unified into one by using a union or an optional/rest parameter',
    'vue/multiline-html-element-content-newline': 'require a line break before and after the contents of a multiline element',
    'vue/no-spaces-around-equal-signs-in-attribute': 'disallow spaces around equal signs in attribute',
    'vue/no-template-shadow': 'disallow variable declarations from shadowing variables declared in the outer scope',
    'vue/singleline-html-element-content-newline': 'require a line break before and after the contents of a singleline element',
    'vue/no-v-html': 'disallow use of v-html to prevent XSS attack'
};

// eslint 规则
exports.eslintRules = {
    'constructor-super': 2,
    'for-direction': 2,
    'getter-return': 2,
    'no-class-assign': 2,
    'no-compare-neg-zero': 2,
    'no-cond-assign': 2,
    'no-const-assign': 2,
    'no-constant-condition': 2,
    'no-control-regex': 2,
    'no-delete-var': 2,
    'no-dupe-args': 2,
    'no-dupe-class-members': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty-character-class': 2,
    'no-empty-pattern': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-semi': 2,
    'no-fallthrough': 2,
    'no-global-assign': 2,
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-misleading-character-class': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-new-symbol': 2,
    'no-obj-calls': 2,
    'no-regex-spaces': 2,
    'no-self-assign': 2,
    'no-sparse-arrays': 2,
    'no-this-before-super': 2,
    'no-undef': 2,
    'no-unexpected-multiline': 2,
    'no-unreachable': 2,
    'no-unsafe-finally': 2,
    'no-unsafe-negation': 2,
    'no-unused-labels': 2,
    'no-useless-escape': 2,
    'require-yield': 2,
    'use-isnan': 2,


    'no-console': 1,
    'no-debugger': 1,
    'no-empty': 1,
    'no-func-assign': 1,
    'no-inner-declarations': 1,
    'no-octal': 1,
    'no-redeclare': 1,
    'no-unused-vars': 1,
    'no-async-promise-executor': 1,
    'no-await-in-loop': 1,
    'no-extra-parens': 1,
    'no-prototype-builtins': 1,
    'no-template-curly-in-string': 1,
    'require-atomic-updates': 2,
    'accessor-pairs': 2,
    'array-callback-return': 2,
    'block-scoped-var': 2,
    'class-methods-use-this': 2,
    'complexity': 1,
    'curly': 2,
    'dot-location': 2,
    'dot-notation': 2,
    'eqeqeq': 2,
    'guard-for-in': 1,
    'no-alert': 2,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-else-return': 2,
    'no-empty-function': 1,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 1,
    'no-extra-label': 1,
    'no-implied-eval': 1,
    'no-invalid-this': 1,
    'no-labels': 1,
    'no-lone-blocks': 1,
    'no-loop-func': 1,
    'no-magic-numbers': 1,
    'no-multi-spaces': 2,
    'no-multi-str': 1,
    'no-new-wrappers': 2,
    'no-octal-escape': 1,
    'no-proto': 2,
    'no-return-assign': 1,
    'no-return-await': 1,
    'no-script-url': 2,
    'no-self-compare': 2,
    'no-sequences': 1,
    'no-throw-literal': 1,
    'no-unmodified-loop-condition': 1,
    'no-unused-expressions': 1,
    'no-useless-call': 1,
    'no-useless-catch': 1,
    'no-useless-concat': 2,
    'no-useless-return': 2,
    'no-warning-comments': 2,
    'no-with': 2,
    'prefer-promise-reject-errors': 1,
    'radix': 2,
    'require-await': 2,
    'wrap-iife': 2,
    'no-restricted-globals': 2,
    'no-shadow-restricted-names': 2,
    'no-undefined': 2,
    'no-use-before-define': 2,
    'callback-return': 1,
    'handle-callback-err': 1,
    'no-buffer-constructor': 1,
    'no-new-require': 1,
    'array-bracket-newline': 2,
    'array-bracket-spacing': 2,
    'array-element-newline': 1,
    'brace-style': 1,
    'comma-dangle': 1,
    'comma-spacing': 2,
    'comma-style': 2,
    'computed-property-spacing': 2,
    'eol-last': 2,
    'func-call-spacing': 2,
    'function-paren-newline': 1,
    'func-names': 1,
    'id-blacklist': 1,
    'indent': 2,
    'jsx-quotes': 2,
    'key-spacing': 2,
    'keyword-spacing': 2,
    'linebreak-style': 1,
    'lines-around-comment': 1,
    'lines-between-class-members': 1,
    'line-comment-position': 2,
    'max-depth': 1,
    'max-len': 2,
    'max-lines': 1,
    'max-lines-per-function': 1,
    'max-nested-callbacks': 1,
    'max-params': 1,
    'max-statements': 1,
    'max-statements-per-line': 2,
    'multiline-comment-style': 2,
    'multiline-ternary': 1,
    'new-parens': 1,
    'newline-per-chained-call': 1,
    'no-array-constructor': 2,
    'no-lonely-if': 1,
    'no-multiple-empty-lines': 2,
    'no-negated-condition': 1,
    'no-new-object': 2,
    'no-tabs': 2,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 1,
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'object-curly-newline': 2,
    'object-curly-spacing': 2,
    'one-var': 2,
    'operator-linebreak': 2,
    'prefer-object-spread': 1,
    'quote-props': 2,
    'quotes': 2,
    'semi': 2,
    'semi-spacing': 2,
    'semi-style': 2,
    'space-before-blocks': 2,
    'space-before-function-paren': 2,
    'space-in-parens': 2,
    'space-infix-ops': 2,
    'space-unary-ops': 2,
    'spaced-comment': 2,
    'switch-colon-spacing': 2,
    'template-tag-spacing': 1,
    'unicode-bom': 1,

    'arrow-body-style': 1,
    'arrow-parens': 2,
    'arrow-spacing': 2,
    'generator-star-spacing': 2,
    'no-confusing-arrow': 2,
    'no-duplicate-imports': 1,
    'no-useless-computed-key': 2,
    'no-useless-constructor': 2,
    'no-useless-rename': 2,
    'no-var': 1,
    'object-shorthand': 1,
    'prefer-arrow-callback': 1,
    'prefer-const': 1,
    'prefer-destructuring': 1,
    'prefer-rest-params': 2,
    'prefer-spread': 1,
    'prefer-template': 1,
    'rest-spread-spacing': 2,
    'symbol-description': 1,
    'template-curly-spacing': 2,
    'yield-star-spacing': 1,
    'import/no-unresolved': 1,
    'import/named': 2,
    'import/default': 2,
    'import/namespace': 2,
    // 'import/no-restricted-paths': 0,
    'import/no-absolute-path': 2,
    'import/no-dynamic-require': 1,
    // 'import/no-internal-modules': 0,
    'import/no-webpack-loader-syntax': 1,
    'import/no-self-import': 2,
    // 'import/no-cycle': 0,
    // 'import/no-relative-parent-imports': 0,
    'import/no-useless-path-segments': 2,
    'import/export': 2,
    'import/no-named-as-default': 2,
    'import/no-named-as-default-member': 2,
    'import/no-deprecated': 2,
    'import/no-extraneous-dependencies': 2,
    'import/no-mutable-exports': 1,
    'import/unambiguous': 2,
    'import/no-commonjs': 1,
    'import/no-amd': 1,
    // 'import/no-nodejs-modules': 0,
    'import/first': 2,
    // 'import/exports-last': 0,
    'import/no-duplicates': 2,
    // 'import/no-namespace': 0,
    'import/extensions': 2,
    'import/order': 1,
    'import/newline-after-import': 2,
    'import/prefer-default-export': 1,
    // 'import/max-dependencies': 0,
    // 'import/no-unassigned-import': 0,
    'import/no-named-default': 2,
    // 'import/no-default-export': 0,
    // 'import/no-named-export': 0,
    // 'import/no-anonymous-default-export': 0,
    // 'import/group-exports': 0,
    'import/dynamic-import-chunkname': 1,
    'new-cap': 0,
    'babel/new-cap': 2,
    'camelcase': 0,
    'babel/camelcase': 2,
    // 'no-invalid-this': 0,
    'babel/no-invalid-this': 1,
    // 'object-curly-spacing': 0,
    'babel/object-curly-spacing': 2,
    // 'quotes': 0,
    'babel/quotes': 2,
    // 'semi': 0,
    'babel/semi': 2,
    // 'no-unused-expressions': 0,
    'babel/no-unused-expressions': 1,
    // 'valid-typeof': 0,
    'babel/valid-typeof': 2,

    'react/boolean-prop-naming': 1,
    'react/button-has-type': 2,
    'react/default-props-match-prop-types': 2,
    'react/destructuring-assignment': 1,
    // 'react/display-name': 0,
    'react/forbid-component-props': 1,
    // 'react/forbid-dom-props': 0,
    // 'react/forbid-elements': 0,
    'react/forbid-foreign-prop-types': 1,
    'react/forbid-prop-types': 1,
    'react/no-access-state-in-setstate': 2,
    'react/no-array-index-key': 2,
    'react/no-children-prop': 2,
    'react/no-danger': 1,
    'react/no-danger-with-children': 2,
    'react/no-deprecated': 2,
    'react/no-did-mount-set-state': 2,
    'react/no-did-update-set-state': 2,
    'react/no-direct-mutation-state': 2,
    'react/no-find-dom-node': 2,
    'react/no-is-mounted': 2,
    'react/no-multi-comp': 2,
    'react/no-redundant-should-component-update': 2,
    'react/no-render-return-value': 2,
    // 'react/no-set-state': 0,
    'react/no-typos': 2,
    'react/no-string-refs': 2,
    'react/no-this-in-sfc': 2,
    'react/no-unescaped-entities': 2,
    'react/no-unknown-property': 2,
    'react/no-unsafe': 2,
    'react/no-unused-prop-types': 2,
    'react/no-unused-state': 2,
    'react/no-will-update-set-state': 2,
    'react/prefer-es6-class': 2,
    'react/prefer-stateless-function': 2,
    'react/prop-types': 2,
    // 'react/react-in-jsx-scope': 0,
    'react/require-default-props': 2,
    // 'react/require-optimization': 0,
    'react/require-render-return': 2,
    'react/self-closing-comp': 2,
    'react/sort-comp': 2,
    // 'react/sort-prop-types': 0,
    'react/style-prop-object': 2,
    'react/void-dom-elements-no-children': 2,
    'react/jsx-boolean-value': 2,
    // 'react/jsx-child-element-spacing': 0,
    'react/jsx-closing-bracket-location': 2,
    'react/jsx-closing-tag-location': 2,
    'react/jsx-curly-spacing': 2,
    'react/jsx-equals-spacing': 2,
    'react/jsx-filename-extension': 2,
    'react/jsx-first-prop-new-line': 2,
    'react/jsx-handler-names': 2,
    'react/jsx-indent': 2,
    'react/jsx-indent-props': 2,
    'react/jsx-key': 2,
    'react/jsx-max-depth': 2,
    'react/jsx-max-props-per-line': 2,
    'react/jsx-no-bind': 2,
    'react/jsx-no-comment-textnodes': 2,
    'react/jsx-no-duplicate-props': 2,
    // 'react/jsx-no-literals': 0,
    'react/jsx-no-target-blank': 2,
    'react/jsx-no-undef': 2,
    'react/jsx-one-expression-per-line': 1,
    'react/jsx-curly-brace-presence': 2,
    'react/jsx-fragments': 1,
    'react/jsx-pascal-case': 2,
    'react/jsx-props-no-multi-spaces': 2,
    // 'react/jsx-sort-default-props': 0,
    // 'react/jsx-sort-props': 0,
    'react/jsx-tag-spacing': 2,
    // 'react/jsx-uses-react': 0,
    'react/jsx-uses-vars': 2,
    'react/jsx-wrap-multilines': 2,
    'react-hooks/rules-of-hooks': 2,

    'jsx-a11y/accessible-emoji': 2,
    'jsx-a11y/alt-text': 2,
    'jsx-a11y/anchor-has-content': 2,
    'jsx-a11y/anchor-is-valid': 2,
    'jsx-a11y/aria-activedescendant-has-tabindex': 2,
    'jsx-a11y/aria-props': 2,
    'jsx-a11y/aria-proptypes': 2,
    'jsx-a11y/aria-role': 2,
    'jsx-a11y/aria-unsupported-elements': 2,
    'jsx-a11y/click-events-have-key-events': 2,
    'jsx-a11y/control-has-associated-label': 1,
    'jsx-a11y/heading-has-content': 2,
    'jsx-a11y/html-has-lang': 2,
    'jsx-a11y/iframe-has-title': 2,
    'jsx-a11y/img-redundant-alt': 2,
    'jsx-a11y/interactive-supports-focus': 2,
    'jsx-a11y/label-has-associated-control': 2,
    'jsx-a11y/label-has-for': 'off',
    'jsx-a11y/media-has-caption': 2,
    'jsx-a11y/mouse-events-have-key-events': 2,
    'jsx-a11y/no-access-key': 2,
    'jsx-a11y/no-autofocus': 2,
    'jsx-a11y/no-distracting-elements': 2,
    'jsx-a11y/no-interactive-element-to-noninteractive-role': 2,
    'jsx-a11y/no-noninteractive-element-interactions': 2,
    'jsx-a11y/no-noninteractive-element-to-interactive-role': 2,
    'jsx-a11y/no-noninteractive-tabindex': 2,
    'jsx-a11y/no-onchange': 2,
    'jsx-a11y/no-redundant-roles': 2,
    'jsx-a11y/no-static-element-interactions': 2,
    'jsx-a11y/role-has-required-aria-props': 2,
    'jsx-a11y/role-supports-aria-props': 2,
    'jsx-a11y/scope': 2,
    'jsx-a11y/tabindex-no-positive': 2,

    'react-native/no-color-literals': 1,
    'react-native/no-inline-styles': 1,
    'react-native/no-raw-text': 2,
    'react-native/no-unused-styles': 2,
    'react-native/split-platform-components': 2,
    // 'react-native/sort-style': 0,

    '@typescript-eslint/no-unused-vars': 1,
    // '@typescript-eslint/interface-name-prefix': 1,
    '@typescript-eslint/array-type': 1,
    '@typescript-eslint/ban-types': 1,
    '@typescript-eslint/member-delimiter-style': 1,
    '@typescript-eslint/no-dynamic-delete': 2,
    '@typescript-eslint/no-explicit-any': 1,
    '@typescript-eslint/no-extra-non-null-assertion': 2,
    '@typescript-eslint/no-extraneous-class': 2,
    '@typescript-eslint/no-for-in-array': 2,
    '@typescript-eslint/no-inferrable-types': 1,
    '@typescript-eslint/no-namespace': 1,
    '@typescript-eslint/no-var-requires': 2,
    '@typescript-eslint/prefer-for-of': 1,
    '@typescript-eslint/prefer-namespace-keyword': 1,
    '@typescript-eslint/prefer-optional-chain': 1,
    '@typescript-eslint/triple-slash-reference': 1,
    '@typescript-eslint/unified-signatures': 1,

    'vue/attribute-hyphenation': 1,
    'vue/html-closing-bracket-newline': 1,
    'vue/html-closing-bracket-spacing': 1,
    'vue/html-end-tags': 1,
    'vue/html-indent': 1,
    'vue/html-quotes': 1,
    'vue/html-self-closing': 1,
    'vue/max-attributes-per-line': 1,
    'vue/multiline-html-element-content-newline': 1,
    'vue/mustache-interpolation-spacing': 1,
    'vue/name-property-casing': 1,
    'vue/no-multi-spaces': 1,
    'vue/no-spaces-around-equal-signs-in-attribute': 1,
    'vue/no-template-shadow': 1,
    'vue/prop-name-casing': 1,
    'vue/require-default-prop': 1,
    'vue/require-prop-types': 1,
    'vue/singleline-html-element-content-newline': 1,
    'vue/v-bind-style': 1,
    'vue/v-on-style': 1,
    'vue/attributes-order': 1,
    'vue/no-v-html': 1,
    'vue/order-in-components': 1,
    'vue/this-in-template': 1,

    // mini
    'mini/comment-directive': 2,
    'mini/xml-indent': 2,
    'mini/no-parsing-error': 2,
    'mini/app-config-acceptable': 2,
    'mini/sitemap-acceptable': 2,
    'mini/no-duplicate-attributes': 2,
    'mini/no-useless-mustache': 2,
    'mini/component-nesting': 2,
    'mini/not-empty': 1,
    'mini/valid-for': 2,
    'mini/valid-if': 2,
    'mini/valid-elif': 2,
    'mini/valid-else': 2,
    'mini/no-confusing-for-if': 2,
    'mini/valid-bind': 2,
    'mini/no-static-inline-styles': 2,
    'mini/component-attributes': 2,
    'mini/max-attributes-per-line': 2,
    'mini/html-end-tags': 2,
    'mini/no-multi-spaces': 2,
    'mini/html-closing-bracket-newline': 2,
    'mini/html-closing-bracket-spacing': 2,
    'mini/no-duplicate-else-if': 2,
    'mini/no-restricted-static-attribute': 2,
    'mini/singleline-html-element-content-newline': 2,
    'mini/html-comment-content-newline': 2,
    'mini/html-comment-content-spacing': 2,
    'mini/no-unknown-component-usage': 1,
    'mini/attribute-value-spacing': 2,
    'mini/resolve-src': 2,

    // eslint-core
    'mini/array-bracket-spacing': 2,
    'mini/arrow-spacing': 2,
    'mini/camelcase': 2,
    'mini/comma-dangle': 2,
    'mini/dot-location': 2,
    'mini/dot-notation': 2,
    'mini/eqeqeq': 2,
    'mini/func-call-spacing': 2,
    'mini/key-spacing': 2,
    'mini/keyword-spacing': 2,
    'mini/mustache-interpolation-spacing': 2,
    'mini/no-spaces-around-equal-signs-in-attribute': 2,
    'mini/no-sparse-arrays': 2,
    'mini/object-curly-newline': 2,
    'mini/object-curly-spacing': 2,
    'mini/space-in-parens': 2,
    'mini/space-unary-ops': 2,
    'mini/no-useless-concat': 2,
    'mini/space-infix-ops': 2,
};

// stylelint 规则
exports.stylelintRules = {
    'mew/white-space-between-values': 1,
    'mew/use-hex-color': 1,
    'mew/strict-values': 2,
    'mew/stylus-colon': 2,
    'mew/stylus-trailing-semicolon': 2,
    'color-no-invalid-hex': 2,
    'font-family-no-duplicate-names': 2,
    'font-family-no-missing-generic-family-keyword': 2,
    'function-calc-no-invalid': 2,
    'function-calc-no-unspaced-operator': 2,
    'function-linear-gradient-no-nonstandard-direction': 2,
    'string-no-newline': 2,
    'unit-no-unknown': 2,
    'property-no-unknown': 2,
    'keyframe-declaration-no-important': 2,
    'declaration-block-no-duplicate-properties': 2,
    'declaration-block-no-shorthand-property-overrides': 2,
    'block-no-empty': 2,
    'selector-pseudo-class-no-unknown': 2,
    'selector-pseudo-element-no-unknown': 2,
    'selector-type-no-unknown': 2,
    'media-feature-name-no-unknown': 2,
    'at-rule-no-unknown': 2,
    'comment-no-empty': 2,
    'no-descending-specificity': 2,
    'no-duplicate-at-import-rules': 2,
    'no-duplicate-selectors': 2,
    'no-empty-source': 2,
    'no-extra-semicolons': 2,
    'no-invalid-double-slash-comments': 2,
    'color-named': 2,
    'function-blacklist': 2,
    'function-url-scheme-blacklist': 2,
    'function-url-scheme-whitelist': 2,
    'shorthand-property-no-redundant-values': 2,
    'value-no-vendor-prefix': 2,
    'property-no-vendor-prefix': 2,
    'declaration-block-no-redundant-longhand-properties': 2,
    'declaration-block-single-line-max-declarations': 1,
    'selector-max-attribute': 2,
    'selector-max-class': 2,
    'selector-max-combinators': 2,
    'selector-max-compound-selectors': 2,
    'selector-max-empty-lines': 2,
    'selector-max-id': 2,
    'selector-max-pseudo-class': 2,
    'selector-max-universal': 2,
    'selector-no-qualifying-type': 2,
    'selector-no-vendor-prefix': 2,
    'at-rule-no-vendor-prefix': 2,
    'at-rule-property-requirelist': 2,
    'max-nesting-depth': 2,
    'no-unknown-animations': 2,
    'color-hex-case': 2,
    'color-hex-length': 2,
    'font-family-name-quotes': 2,
    'font-weight-notation': 2,
    'function-comma-space-after': 2,
    'function-comma-space-before': 2,
    'function-max-empty-lines': 2,
    'function-name-case': 2,
    'function-parentheses-space-inside': 2,
    'function-url-quotes': 2,
    'function-whitespace-after': 2,
    'number-leading-zero': 2,
    'number-no-trailing-zeros': 2,
    'string-quotes': 2,
    'length-zero-no-unit': 2,
    'unit-case': 2,
    'value-keyword-case': 2,
    'value-list-comma-newline-after': 2,
    'value-list-comma-space-after': 2,
    'value-list-comma-space-before': 2,
    'custom-property-empty-line-before': 2,
    'property-case': 2,
    'declaration-bang-space-after': 2,
    'declaration-bang-space-before': 2,
    'declaration-colon-space-after': 2,
    'declaration-colon-space-before': 2,
    'declaration-block-semicolon-newline-after': 2,
    'declaration-block-semicolon-space-after': 2,
    'declaration-block-semicolon-space-before': 2,
    'declaration-block-trailing-semicolon': 2,
    'block-closing-brace-empty-line-before': 2,
    'block-closing-brace-newline-after': 2,
    'block-closing-brace-newline-before': 2,
    'block-opening-brace-newline-after': 2,
    'block-opening-brace-space-before': 2,
    'selector-attribute-brackets-space-inside': 2,
    'selector-attribute-operator-space-after': 2,
    'selector-attribute-operator-space-before': 2,
    'selector-attribute-quotes': 2,
    'selector-combinator-space-after': 2,
    'selector-combinator-space-before': 2,
    'selector-descendant-combinator-no-non-space': 2,
    'selector-pseudo-class-case': 2,
    'selector-pseudo-class-parentheses-space-inside': 2,
    'selector-pseudo-element-case': 2,
    'selector-pseudo-element-colon-notation': 2,
    'selector-type-case': 2,
    'selector-list-comma-newline-after': 2,
    'selector-list-comma-space-before': 2,
    'rule-empty-line-before': 2,
    'media-feature-colon-space-after': 2,
    'media-feature-colon-space-before': 2,
    'media-feature-name-case': 2,
    'media-feature-parentheses-space-inside': 2,
    'media-feature-range-operator-space-after': 2,
    'media-feature-range-operator-space-before': 2,
    'media-query-list-comma-space-after': 2,
    'media-query-list-comma-space-before': 2,
    'at-rule-empty-line-before': 2,
    'at-rule-name-case': 2,
    'at-rule-name-newline-after': 2,
    'at-rule-name-space-after': 2,
    'at-rule-semicolon-newline-after': 2,
    'at-rule-semicolon-space-before': 2,
    'comment-empty-line-before': 2,
    'comment-whitespace-inside': 2,
    'indentation': 2,
    'linebreaks': 2,
    'max-empty-lines': 2,
    'max-line-length': 2,
    'no-eol-whitespace': 2,
    'no-missing-end-of-source-newline': 2,
    'no-empty-first-line': 2,
};

// htmlint 规则
exports.htmlintRules = {
    'asset-type': 1,
    'bool-attribute-value': 1,
    'button-name': 1,
    'button-type': 1,
    'charset': 1,
    'css-in-head': 1,
    'doctype': 1,
    'html-lang': 1,
    'ie-edge': 1,
    'img-alt': 1,
    'img-src': 1,
    'img-title': 1,
    'img-width-height': 1,
    'indent-char': 2,
    'lowercase-class-with-hyphen': 1,
    'lowercase-id-with-hyphen': 1,
    'nest': 1,
    'rel-stylesheet': 1,
    'script-in-tail': 1,
    'title-required': 1,
    'unique-id': 1,
    'no-duplication-id-and-name': 1,
    'no-meta-css': 2,
    'no-hook-class': 2,
    'max-len': 2,
    'no-bom': 1,
    'viewport': 1,
    'label-for-input': 1,
    'attr-lowercase': 1,
    'attr-no-duplication': 1,
    'attr-unsafe-chars': 1,
    'attr-value-double-quotes': 1,
    'id-class-ad-disabled': 1,
    'spec-char-escape': 1,
    'self-close': 2,
    'style-disabled': 1,
    'tag-pair': 1,
    'tagname-lowercase': 1,
    'script-content': 1,
    'style-content': 1,
};
