module.exports = {
    extends: require.resolve('./base'),
    rules: {
        '@mewjs/mini/app-config-acceptable': 2,
        '@mewjs/mini/sitemap-acceptable': 2,
        '@mewjs/mini/no-duplicate-attributes': 2,
        '@mewjs/mini/no-useless-mustache': [2, { ignoreStringEscape: true }],
        '@mewjs/mini/component-nesting': [2, { allowEmptyBlock: false, ignoreEmptyBlock: ['view'] }],
        '@mewjs/mini/not-empty': 1,
        '@mewjs/mini/valid-for': [2, { withKey: false }],
        '@mewjs/mini/valid-if': 2,
        '@mewjs/mini/valid-elif': 2,
        '@mewjs/mini/valid-else': 2,
        '@mewjs/mini/no-confusing-for-if': 2,
        '@mewjs/mini/valid-bind': 2,
        '@mewjs/mini/no-static-inline-styles': [2, { allowBinding: true }],
        '@mewjs/mini/component-attributes': [2, { allowEmpty: false }],
        '@mewjs/mini/max-attributes-per-line': [2, { singleline: 5, multiline: 1 }],
        '@mewjs/mini/html-end-tags': 2,
        '@mewjs/mini/no-multi-spaces': 2,
        '@mewjs/mini/html-closing-bracket-newline': 2,
        '@mewjs/mini/html-closing-bracket-spacing': 2,
        '@mewjs/mini/no-duplicate-else-if': 2,
        '@mewjs/mini/no-restricted-static-attribute': 2,
        '@mewjs/mini/singleline-html-element-content-newline': 2,
        '@mewjs/mini/html-comment-content-newline': 2,
        '@mewjs/mini/html-comment-content-spacing': 2,
        '@mewjs/mini/no-unknown-component-usage': 1,
        '@mewjs/mini/attribute-value-spacing': 2,
        '@mewjs/mini/resolve-src': 2,

        // eslint-core
        '@mewjs/mini/array-bracket-spacing': 2,
        '@mewjs/mini/arrow-spacing': 2,
        '@mewjs/mini/camelcase': 2,
        '@mewjs/mini/comma-dangle': 2,
        '@mewjs/mini/dot-location': [2, 'property'],
        '@mewjs/mini/dot-notation': 2,
        '@mewjs/mini/eqeqeq': 2,
        '@mewjs/mini/func-call-spacing': 2,
        '@mewjs/mini/key-spacing': 2,
        '@mewjs/mini/keyword-spacing': 2,
        '@mewjs/mini/mustache-interpolation-spacing': [2, 'never'],
        '@mewjs/mini/no-spaces-around-equal-signs-in-attribute': 2,
        '@mewjs/mini/no-sparse-arrays': 2,
        '@mewjs/mini/object-curly-newline': 2,
        '@mewjs/mini/object-curly-spacing': 2,
        '@mewjs/mini/space-in-parens': 2,
        '@mewjs/mini/space-unary-ops': 2,
        '@mewjs/mini/no-useless-concat': 2,
        '@mewjs/mini/space-infix-ops': 2,
    }
};
